version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      # If desired mount a location to use for letsencrypt autorenew using the webroot plugin e.g.
      # - type: bind                      #allow certbot to write into the docker container without restarting anything
      #   source:  /usr/share/nginx/html/ #default webroot location on ubuntu, this can be anywhere that is mountable and docker will have perms to access
      #   target: /etc/nginx/html         #default webroot inside the nginx:latest container at time of commit, needs to match to a root in an nginx.conf location block
    ports:
      - 80:80
      - 443:443
    restart: always

  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
      # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend for development
    volumes:
      - "./pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "./pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
      - "./pigallery2/tmp:/app/data/tmp" # CHANGE ME
    expose:
      - "80"
    restart: always

volumes:
  db-data:
